name: demix-env
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab
  - python
  - numpy
  - qgrid
  - matplotlib
  - nodejs
  - pip
  - pip:
    - npm
    - ipywidgets
    - pandas
    - seaborn
    - qgrid
    - scipy
    - jupyter_contrib_nbextensions 
