name: demix-env
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - python
  - numpy
  - qgrid
  - matplotlib>=2.1.1
  - pip
  - pip:
    - ipywidgets
    - pandas
    - seaborn
    - qgrid
    - scipy
    - jupyter_contrib_nbextensions
