#!/bin/bash

jupyter labextension install @jupyter-widgets/jupyterlab-manager qgrid

jupyter contrib nbextension install --user
jupyter nbextension enable --py qgrid
jupyter nbextension enable --py widgetsnbextension
